In [1]:
# API
!pip install requests

Requirement already satisfied: requests in c:\users\acer\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\acer\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\acer\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\acer\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\acer\anaconda3\lib\site-packages (from requests) (2025.8.3)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import requests

In [3]:
url = "https://cataas.com/api/cats?tags=cute"
res = requests.get(url)
res

In [4]:
data = res.json()
data

[{'id': '0F0IKAPOdWiE755P',
  'tags': ['meet', 'cute'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-06-18T09:46:45.702Z'},
 {'id': '0GC9MRUAqxhBzPyA',
  'tags': ['cute'],
  'mimetype': 'image/png',
  'createdAt': '2024-09-15T15:45:25.375Z'},
 {'id': '0mstmOIucwiN80jb',
  'tags': ['cute', 'black'],
  'mimetype': 'image/jpeg',
  'createdAt': '2023-10-25T00:04:03.771Z'},
 {'id': '0RU7ZkgzyvWv8UJG',
  'tags': ['tuxedo', 'computer', 'sleepy', 'cute', 'sleeping'],
  'mimetype': 'image/png',
  'createdAt': '2024-04-20T22:52:58.132Z'},
 {'id': '0ztFbDrgDV2K7yJ1',
  'tags': ['cute', 'orange', 'funny', 'lasagna', 'garfield'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-08-23T20:15:26.393Z'},
 {'id': '1bJraW0IwSPm3MVd',
  'tags': ['cute', 'fluffy'],
  'mimetype': 'image/jpeg',
  'createdAt': '2022-04-27T01:49:50.792Z'},
 {'id': '1CF7xZmlX0t8QpgP',
  'tags': ['ange', 'cute'],
  'mimetype': 'image/jpeg',
  'createdAt': '2016-11-22T05:38:06.656Z'},
 {'id': '1DrcyohjhwcNaRIz',
  'tags': ['cute', 'orange', 'sleepy', 'tired', 'outside', 'grass'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-02-29T00:49:57.420Z'},
 {'id': '1KeQpy7eHqi0SFmc',
  'tags': ['orange', 'cute', 'lying', 'bed', 'blanket'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-10-08T23:54:00.959Z'},
 {'id': '1N2AH31jiY6N9TYc',
  'tags': ['cute', 'mlem'],
  'mimetype': 'image/jpeg',
  'createdAt': '2024-02-08T07:59:29.085Z'}]

In [5]:
import pandas as pd

In [6]:
df = pd.json_normalize(data)
df

,id,tags,mimetype,createdAt
0,0F0IKAPOdWiE755P,"[meet, cute]",image/jpeg,2024-06-18T09:46:45.702Z
1,0GC9MRUAqxhBzPyA,[cute],image/png,2024-09-15T15:45:25.375Z
2,0mstmOIucwiN80jb,"[cute, black]",image/jpeg,2023-10-25T00:04:03.771Z
3,0RU7ZkgzyvWv8UJG,"[tuxedo, computer, sleepy, cute, sleeping]",image/png,2024-04-20T22:52:58.132Z
4,0ztFbDrgDV2K7yJ1,"[cute, orange, funny, lasagna, garfield]",image/jpeg,2024-08-23T20:15:26.393Z
5,1bJraW0IwSPm3MVd,"[cute, fluffy]",image/jpeg,2022-04-27T01:49:50.792Z
6,1CF7xZmlX0t8QpgP,"[ange, cute]",image/jpeg,2016-11-22T05:38:06.656Z
7,1DrcyohjhwcNaRIz,"[cute, orange, sleepy, tired, outside, grass]",image/jpeg,2024-02-29T00:49:57.420Z
8,1KeQpy7eHqi0SFmc,"[orange, cute, lying, bed, blanket]",image/jpeg,2024-10-08T23:54:00.959Z
9,1N2AH31jiY6N9TYc,"[cute, mlem]",image/jpeg,2024-02-08T07:59:29.085Z

In [7]:
#Requests
url = "https://scrapethissite.com/pages/simple/"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0 Safari/537.36"
}
res = requests.get(url, headers=headers)
res

In [8]:
print(res.status_code)
# print(res.content)
print("-------")
print(res.headers)

200
-------
{'Date': 'Sat, 03 Jan 2026 07:53:45 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=%2FoZytR5BACdZLoy141aiQycJhRdBVuPgdHtJ%2B7htnIo%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1767426825"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=%2FoZytR5BACdZLoy141aiQycJhRdBVuPgdHtJ%2B7htnIo%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1767426825"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9b80ec9a7a629ffc-AMS', 'alt-svc': 'h3=":443"; ma=86400'}

In [9]:
# if res.status_code == 200:
#     print(res.text)

In [10]:
with open("scraped_data/data1.html", "w", encoding = "utf-8") as f:
    f.write(res.text)

In [11]:
# BeautifulSoup
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\acer\anaconda3\lib\site-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\acer\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\acer\anaconda3\lib\site-packages (from beautifulsoup4) (4.12.2)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
from bs4 import BeautifulSoup
with open("scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [13]:
# soup

In [14]:
soup.find("h3")

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [15]:
soup.h3

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [16]:
all_h3 = soup.find_all("h3")
type(all_h3)

bs4.element.ResultSet

In [26]:
all_countries = []
for h3 in all_h3:
    name = h3.get_text(strip = True) #country names
    # print(h3.find_parent("div")["class"])
    population = h3.find_next("div").select("span.country-population")[0].get_text(strip = True) #country population

    all_countries.append([name, population])

In [27]:
all_countries

[['Andorra', '84000'],
 ['United Arab Emirates', '4975593'],
 ['Afghanistan', '29121286'],
 ['Antigua and Barbuda', '86754'],
 ['Anguilla', '13254'],
 ['Albania', '2986952'],
 ['Armenia', '2968000'],
 ['Angola', '13068161'],
 ['Antarctica', '0'],
 ['Argentina', '41343201'],
 ['American Samoa', '57881'],
 ['Austria', '8205000'],
 ['Australia', '21515754'],
 ['Aruba', '71566'],
 ['Ã…land', '26711'],
 ['Azerbaijan', '8303512'],
 ['Bosnia and Herzegovina', '4590000'],
 ['Barbados', '285653'],
 ['Bangladesh', '156118464'],
 ['Belgium', '10403000'],
 ['Burkina Faso', '16241811'],
 ['Bulgaria', '7148785'],
 ['Bahrain', '738004'],
 ['Burundi', '9863117'],
 ['Benin', '9056010'],
 ['Saint BarthÃ©lemy', '8450'],
 ['Bermuda', '65365'],
 ['Brunei', '395027'],
 ['Bolivia', '9947418'],
 ['Bonaire', '18012'],
 ['Brazil', '201103330'],
 ['Bahamas', '301790'],
 ['Bhutan', '699847'],
 ['Bouvet Island', '0'],
 ['Botswana', '2029307'],
 ['Belarus', '9685000'],
 ['Belize', '314522'],
 ['Canada', '33679000'],
 ['Cocos [Keeling] Islands', '628'],
 ['Democratic Republic of the Congo', '70916439'],
 ['Central African Republic', '4844927'],
 ['Republic of the Congo', '3039126'],
 ['Switzerland', '7581000'],
 ['Ivory Coast', '21058798'],
 ['Cook Islands', '21388'],
 ['Chile', '16746491'],
 ['Cameroon', '19294149'],
 ['China', '1330044000'],
 ['Colombia', '47790000'],
 ['Costa Rica', '4516220'],
 ['Cuba', '11423000'],
 ['Cape Verde', '508659'],
 ['Curacao', '141766'],
 ['Christmas Island', '1500'],
 ['Cyprus', '1102677'],
 ['Czech Republic', '10476000'],
 ['Germany', '81802257'],
 ['Djibouti', '740528'],
 ['Denmark', '5484000'],
 ['Dominica', '72813'],
 ['Dominican Republic', '9823821'],
 ['Algeria', '34586184'],
 ['Ecuador', '14790608'],
 ['Estonia', '1291170'],
 ['Egypt', '80471869'],
 ['Western Sahara', '273008'],
 ['Eritrea', '5792984'],
 ['Spain', '46505963'],
 ['Ethiopia', '88013491'],
 ['Finland', '5244000'],
 ['Fiji', '875983'],
 ['Falkland Islands', '2638'],
 ['Micronesia', '107708'],
 ['Faroe Islands', '48228'],
 ['France', '64768389'],
 ['Gabon', '1545255'],
 ['United Kingdom', '62348447'],
 ['Grenada', '107818'],
 ['Georgia', '4630000'],
 ['French Guiana', '195506'],
 ['Guernsey', '65228'],
 ['Ghana', '24339838'],
 ['Gibraltar', '27884'],
 ['Greenland', '56375'],
 ['Gambia', '1593256'],
 ['Guinea', '10324025'],
 ['Guadeloupe', '443000'],
 ['Equatorial Guinea', '1014999'],
 ['Greece', '11000000'],
 ['South Georgia and the South Sandwich Islands', '30'],
 ['Guatemala', '13550440'],
 ['Guam', '159358'],
 ['Guinea-Bissau', '1565126'],
 ['Guyana', '748486'],
 ['Hong Kong', '6898686'],
 ['Heard Island and McDonald Islands', '0'],
 ['Honduras', '7989415'],
 ['Croatia', '4491000'],
 ['Haiti', '9648924'],
 ['Hungary', '9982000'],
 ['Indonesia', '242968342'],
 ['Ireland', '4622917'],
 ['Israel', '7353985'],
 ['Isle of Man', '75049'],
 ['India', '1173108018'],
 ['British Indian Ocean Territory', '4000'],
 ['Iraq', '29671605'],
 ['Iran', '76923300'],
 ['Iceland', '308910'],
 ['Italy', '60340328'],
 ['Jersey', '90812'],
 ['Jamaica', '2847232'],
 ['Jordan', '6407085'],
 ['Japan', '127288000'],
 ['Kenya', '40046566'],
 ['Kyrgyzstan', '5776500'],
 ['Cambodia', '14453680'],
 ['Kiribati', '92533'],
 ['Comoros', '773407'],
 ['Saint Kitts and Nevis', '51134'],
 ['North Korea', '22912177'],
 ['South Korea', '48422644'],
 ['Kuwait', '2789132'],
 ['Cayman Islands', '44270'],
 ['Kazakhstan', '15340000'],
 ['Laos', '6368162'],
 ['Lebanon', '4125247'],
 ['Saint Lucia', '160922'],
 ['Liechtenstein', '35000'],
 ['Sri Lanka', '21513990'],
 ['Liberia', '3685076'],
 ['Lesotho', '1919552'],
 ['Lithuania', '2944459'],
 ['Luxembourg', '497538'],
 ['Latvia', '2217969'],
 ['Libya', '6461454'],
 ['Morocco', '31627428'],
 ['Monaco', '32965'],
 ['Moldova', '4324000'],
 ['Montenegro', '666730'],
 ['Saint Martin', '35925'],
 ['Madagascar', '21281844'],
 ['Marshall Islands', '65859'],
 ['Macedonia', '2062294'],
 ['Mali', '13796354'],
 ['Myanmar [Burma]', '53414374'],
 ['Mongolia', '3086918'],
 ['Macao', '449198'],
 ['Northern Mariana Islands', '53883'],
 ['Martinique', '432900'],
 ['Mauritania', '3205060'],
 ['Montserrat', '9341'],
 ['Malta', '403000'],
 ['Mauritius', '1294104'],
 ['Maldives', '395650'],
 ['Malawi', '15447500'],
 ['Mexico', '112468855'],
 ['Malaysia', '28274729'],
 ['Mozambique', '22061451'],
 ['Namibia', '2128471'],
 ['New Caledonia', '216494'],
 ['Niger', '15878271'],
 ['Norfolk Island', '1828'],
 ['Nigeria', '154000000'],
 ['Nicaragua', '5995928'],
 ['Netherlands', '16645000'],
 ['Norway', '5009150'],
 ['Nepal', '28951852'],
 ['Nauru', '10065'],
 ['Niue', '2166'],
 ['New Zealand', '4252277'],
 ['Oman', '2967717'],
 ['Panama', '3410676'],
 ['Peru', '29907003'],
 ['French Polynesia', '270485'],
 ['Papua New Guinea', '6064515'],
 ['Philippines', '99900177'],
 ['Pakistan', '184404791'],
 ['Poland', '38500000'],
 ['Saint Pierre and Miquelon', '7012'],
 ['Pitcairn Islands', '46'],
 ['Puerto Rico', '3916632'],
 ['Palestine', '3800000'],
 ['Portugal', '10676000'],
 ['Palau', '19907'],
 ['Paraguay', '6375830'],
 ['Qatar', '840926'],
 ['RÃ©union', '776948'],
 ['Romania', '21959278'],
 ['Serbia', '7344847'],
 ['Russia', '140702000'],
 ['Rwanda', '11055976'],
 ['Saudi Arabia', '25731776'],
 ['Solomon Islands', '559198'],
 ['Seychelles', '88340'],
 ['Sudan', '35000000'],
 ['Sweden', '9828655'],
 ['Singapore', '4701069'],
 ['Saint Helena', '7460'],
 ['Slovenia', '2007000'],
 ['Svalbard and Jan Mayen', '2550'],
 ['Slovakia', '5455000'],
 ['Sierra Leone', '5245695'],
 ['San Marino', '31477'],
 ['Senegal', '12323252'],
 ['Somalia', '10112453'],
 ['Suriname', '492829'],
 ['South Sudan', '8260490'],
 ['SÃ£o TomÃ© and PrÃ\xadncipe', '175808'],
 ['El Salvador', '6052064'],
 ['Sint Maarten', '37429'],
 ['Syria', '22198110'],
 ['Swaziland', '1354051'],
 ['Turks and Caicos Islands', '20556'],
 ['Chad', '10543464'],
 ['French Southern Territories', '140'],
 ['Togo', '6587239'],
 ['Thailand', '67089500'],
 ['Tajikistan', '7487489'],
 ['Tokelau', '1466'],
 ['East Timor', '1154625'],
 ['Turkmenistan', '4940916'],
 ['Tunisia', '10589025'],
 ['Tonga', '122580'],
 ['Turkey', '77804122'],
 ['Trinidad and Tobago', '1228691'],
 ['Tuvalu', '10472'],
 ['Taiwan', '22894384'],
 ['Tanzania', '41892895'],
 ['Ukraine', '45415596'],
 ['Uganda', '33398682'],
 ['U.S. Minor Outlying Islands', '0'],
 ['United States', '310232863'],
 ['Uruguay', '3477000'],
 ['Uzbekistan', '27865738'],
 ['Vatican City', '921'],
 ['Saint Vincent and the Grenadines', '104217'],
 ['Venezuela', '27223228'],
 ['British Virgin Islands', '21730'],
 ['U.S. Virgin Islands', '108708'],
 ['Vietnam', '89571130'],
 ['Vanuatu', '221552'],
 ['Wallis and Futuna', '16025'],
 ['Samoa', '192001'],
 ['Kosovo', '1800000'],
 ['Yemen', '23495361'],
 ['Mayotte', '159042'],
 ['South Africa', '49000000'],
 ['Zambia', '13460305'],
 ['Zimbabwe', '11651858']]

In [31]:
import pandas as pd
df = pd.DataFrame(all_countries, columns = ["Name", "Population"])
df

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

In [32]:
df.to_csv("scraped_data/data1_cleaned.csv", index = True)